import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from 'next/font/google'; // Note the underscore for multi-word font names

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures text is visible while the font loads
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
